version: '3.7'
services:
  app:
   build: app
   restart: always
   ports:
     - 5007:5000
   environment:
     - DEBUG=1
   networks:
      - reddit_save_network

  client:
   build: client
   restart : always
   ports:
     - 3002:80
   environment:
     - CHOKIDAR_USEPOLLING=true
   networks:
     - reddit_save_network
   depends_on:
     - app

  proxy:
    build: proxy
    restart: always
    ports:
      - 8000:80
    networks:
      - reddit_save_network
    depends_on:
      - app
      - client

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - reddit_save_network
    volumes:
      - mongo_data:/data/db mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    volumes:
      - mongo_data:/data/db
    depends_on:
      - mongo
    networks:
      - reddit_save_network

networks:
  reddit_save_network:

volumes:
  mongo_data:
