version: "3"
services:
  reverse-proxy:
    # build:
    #   context: ./reverse_proxy
    #   dockerfile: Dockerfile
    image: nginx
    volumes: 
      - ./reverse_proxy:/etc/nginx
    depends_on:
      - frontend
      - backend
    ports: 
      - 80:80
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/code
    depends_on:
      - mongodb
    ports:
      - 5000:5000
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
    - ./client:/app
    - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  mongodb:
    image: mongo:3.6.23
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin123
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - ./.mongo-db-data/:/data/db 
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d/
    command: mongod